### ISSUE TITLE
Add projections based on SMILES/chem features

### ISSUE THREAD

**Issue by azywot** [zuzg/drug-screening#148]

**Comment by zuzg** [comment]
inspo: [https://blog.reverielabs.com/mapping-chemical-space-with-umap/](https://blog.reverielabs.com/mapping-chemical-space-with-umap/?fbclid=IwAR3PLS2yqOlroSo395XGDnnb8A3Mwl6MNtHVN9ihXfmx0tn3CF2lO0UrjUs)
